name:                icfpc2022
version:             0.1.0.0
github:              "nobsun/icfpc2022"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2022 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2022#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- hspec
- main-tester
- gloss
- containers
- array
- vector
- mtl
- JuicyPixels
- primitive

library:
  source-dirs: src

executables:
  icfpc2022:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
  average-color:
    main:                Main.hs
    source-dirs:         app/average-color
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
  mosaic-color:
    main:                Main.hs
    source-dirs:         app/mosaic-color
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
  eval:
    main:                Main.hs
    source-dirs:         app/eval
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
    - optparse-applicative

tests:
  icfpc2022-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
    - hspec
    - main-tester

  icfpc2022-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2022
    - doctest
